// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faojhjsnmhffdhiomojm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhb2poanNubWhmZmRoaW9tb2ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDE0ODAsImV4cCI6MjA1NzYxNzQ4MH0.m7zmeFR2G4tT1TpsgyyEu1lLZo3csMNZOgO0BjCKmxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);